name: Ubuntu with SSH (ngrok)

on:
  workflow_dispatch:
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH via ngrok
        uses: lbbboy/ssh2actions@main
        with:
          mode: ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: us
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
         retain_days: 0
         keep_minimum_runs: 1
