name: Ubuntu with SSH (cloudflared)

on:
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH via cloudflared
        uses: P3TERX/ssh2actions@main
        with:
          mode: cloudflared
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
